name: IITM Assignment Action

on:
  workflow_dispatch:   # Lets you run it manually

jobs:
  test-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: 23f2005050@ds.study.iitm.ac.in
        run: echo "This step contains my email as required"

      - name: Say hello
        run: echo "GitHub Actions is working!"
